In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Define Vocabulary size
voc_size = 10000

In [5]:
## One Hot Representaiton
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3198, 2926, 4068, 1627],
 [3198, 2926, 4068, 2948],
 [3198, 949, 4068, 7591],
 [9576, 775, 2695, 8988, 53],
 [9576, 775, 2695, 8988, 3060],
 [7331, 3198, 2451, 4068, 4999],
 [4071, 2633, 1254, 8988]]

In [20]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding, Dense
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np 

In [12]:
sent_length = 8
embeded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen = sent_length)
embeded_docs

array([[   0,    0,    0,    0, 3198, 2926, 4068, 1627],
       [   0,    0,    0,    0, 3198, 2926, 4068, 2948],
       [   0,    0,    0,    0, 3198,  949, 4068, 7591],
       [   0,    0,    0, 9576,  775, 2695, 8988,   53],
       [   0,    0,    0, 9576,  775, 2695, 8988, 3060],
       [   0,    0,    0, 7331, 3198, 2451, 4068, 4999],
       [   0,    0,    0,    0, 4071, 2633, 1254, 8988]], dtype=int32)

In [14]:
## feature representation
dim = 10 

In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step


array([[[ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.01182947,  0.03977043, -0.0436377 ,  0.00432007,
         -0.0182821 ,  0.02407486, -0.0445848 , -0.03149565,
          0.0338713 , -0.02101804],
        [ 0.02550187,  0.0344411 , -0.04635775,  0.04384348,
          0.0135823 ,  0.01867427,  0.04867763,  0.04290941,
         -0.03508475,  0.0331347 ],
        [-0.03405157,  0.04876201,  0.04879005, -0.0

In [37]:
embeded_docs[0]

array([   0,    0,    0,    0, 3198, 2926, 4068, 1627], dtype=int32)

In [39]:
model.predict(embeded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.03224931, -0.01905992, -0.03387039,  0.04124869,
         -0.00282266,  0.01936323,  0.03963769, -0.0442106 ,
         -0.00732462, -0.0343776 ],
        [ 0.01182947,  0.03977043, -0.0436377 ,  0.00432007,
         -0.0182821 ,  0.02407486, -0.0445848 , -0.03149565,
          0.0338713 , -0.02101804],
        [ 0.02550187,  0.0344411 , -0.04635775,  0.04384348,
          0.0135823 ,  0.01867427,  0.04867763,  0.04290941,
         -0.03508475,  0.0331347 ],
        [-0.03405157,  0.04876201,  0.04879005, -0.0